name: Build Debs

# Controls when the workflow will run
on:
  workflow_dispatch

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64/v8, linux/arm/v7 ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Dpkg-buildpackages
        uses: addnab/docker-run-action@v3
        with:
          image: ubuntu:16.04
          shell: bash
          options: -v ${{ github.workspace }}:/workdir --platform ${{ matrix.platform }}
          run: |
            apt update -qq
            apt install -y g++ make fakeroot debhelper
            cd /workdir/src 
            dpkg-buildpackage -b -j"$(nproc)"

      - uses: actions/upload-artifact@v3
        with:
          name: arducam-config-parser-dev
          path: arducam-config-parser-dev*.deb
